### PR TITLE
Update to TypeShape 7.0.0.

### PR DESCRIPTION
**Pull request by Rajivhost**
Hi,
I made some changes regarding TypeShape update to 7.0.0.
The project builds, but there is still a test which fail

image

### CODE REVIEW

**Comment by Rajivhost** [comment]
Weird, all succeeded on AppVeyor and Travis.
But on my machine, I still got this

image

**Comment by demystifyfp** [comment]
It looks like there are breaking changes in Typeshape 7.0. Is this pull request covers all?

**Comment by Rajivhost** [comment]
Yes, I made all necessary changes.

**Comment by Rajivhost** [comment]
Hi,
Any updates regarding this PR?

**Comment by demystifyfp** [comment]
Sorry @Rajivhost, I am out of town with limited access to the internet. Will do it over this weekend.

**Comment by Rajivhost** [comment]
Ok, no worries, I'm waiting.

**Comment by demystifyfp** [comment]
Thanks, @Rajivhost for submitting the pull request. It's now available in the [latest version](https://www.nuget.org/packages/FsConfig/2.1.3)

**Pull request merged**
