### PR TITLE
Restrict to TypeShape <8

### PR DESCRIPTION
**Pull request by piaste**
TypeShape 8 has just been released and it's got breaking changes for FsConfig (I haven't yet determined which).

Any project that uses FsConfig and runs `paket update` will break.

I've added a `< 8.0` restriction in `paket.dependencies` and run `paket update` to update the lock.

However, I can't run tests on the updated build. They give this error message:

```
Unable to find D:\repos\FsConfig\tests\FsConfig.Tests\bin\Debug\netcoreapp2.0\testhost.dll. Please publish your test project and retry.
```

and running a successful `dotnet publish -f netcoreapp2.0` on the test project doesn't help. Any clue on getting the tests to run?

### CODE REVIEW

**Comment by demystifyfp** [comment]
Hi, @piaste, Thanks for reporting & submitting the pull request. Sorry for the delayed reply. I will check and update this by Friday.

**Comment by demystifyfp** [comment]
@piaste It is fixed in the `2.1.4` version. Would you be able to double-check?

**Comment by piaste** [comment]
```
Paket version 5.226.0
NuGet typeshape - 7.1 is a direct (paket.dependencies) dependency.
It is part of following dependency chains:

-> FsConfig - 2.1.4
  -> typeshape - 7.1

Performance:
 - Runtime: 1 second
````

Works. Thanks for the fix :)

Do you have any idea of what the problem with the test setup could be? I'd like to submit a couple of non-trivial PRs as soon as I can, and those will need tests to pass.

**Comment by demystifyfp** [comment]
Extremely sorry @piaste for the delayed reply. I somehow missed the notification email of your comment. 

I am not sure what the fix was and I guess it might be due to the outdated build script. When I build it from my machine it worked.

**Pull request closed without merging**
