### PR TITLE
Ignore case enum

### PR DESCRIPTION
**Pull request by piaste**
It's idiomatic to give PascalCase names to .NET enums, but environment variables are more commonly written in ALLCAPS. I have forgotten multiple times to write values in PascalCase, resulting in a crash at startup.

This PR enables the `ignoreCase` flag in the `TryParse` invocation for enum values.

It could be a breaking change *if* somebody had multiple enum cases distinguished only by case, which is technically possible. I'm not aware of any legitimate reasons to do so.

### CODE REVIEW

**Comment by demystifyfp** [comment]
Thanks, @piaste for the pull request.

Can you clarify the below sentence

> It's idiomatic to give PascalCase names to .NET enums, but environment variables are more commonly written in ALLCAPS. 

To my understanding, the only the names of the environment variables are written in all upper case format and the value can be in any format. 

For an enum like below,

```fsharp
  [<Flags>]
  type Color =
  | Red = 0
  | Blue = 1
  | Green = 2
  | RedGreenBlue = 3
```

with the following environment variable value,

```bash
ENV_ENUM_STRING="RedGreenBlue"
```

```fsharp
EnvConfig.Get<Color> "ENV_ENUM_STRING" 
```

will return `Ok Color.RedGreenBlue`

Am I missing anything obvious here?

**Comment by piaste** [comment]
Thank you for the feedback, and of course the project.

The value can be case-sensitive in string fields such as passwords or Unix paths, but when the field is an enum, in my experience, it generally corresponds to a command-line flag which is expected to be case insensitive (or all-lower or all-upper, but virtually never PascalCase).

In our project the issue emerged with the following settings:

 - a LOG_LEVEL setting, where the values are the standard verbose / debug / informative / warning / error from the logging library (Serilog). Multiple developers were surprised when they set it to "DEBUG" or "debug" and it resulted in a crash. It didn't feel 'right' to have to set it to "Debug" specifically

 - an ENVIRONMENT setting with the values. In this case we had control over the F# enum, so we could at least define it as | DEV | STAGING | PROD in all caps, but we couldn't extend the convention to library-defined enums.

In your example, I believe the PR wouldn't break anything? `RedGreenBlue` would still load as `3`, and so would `REDGREENBLUE`. I could add a test for that if you like.

**Comment by demystifyfp** [comment]
Thanks, @piaste for the detailed explanation. Now, I understand your scenario, and it makes sense as well. 

I have a suggestion. 

Instead of assuming the enums as always case insensitive, how about providing an option to specify it explicitly via attributes like 

```fsharp
type Config = {

  DbConnString : string
  
  [<IgnoreCase(true)>]
  LogLevel : LogLevel

  [<IgnoreCase(true)>]
  Environment : Environment
}
```

It is straight-forward to add this new attribute. Here is a high-level change you need to do

* Add `IgnoreCase` property in [FieldValueParseArgs](https://github.com/demystifyfp/FsConfig/blob/master/src/FsConfig/Config.fs#L203)
* Try to get the `IgnoreCase` attribute value and if not present make it false by default. Refer [this](https://github.com/demystifyfp/FsConfig/blob/master/src/FsConfig/Config.fs#L243) this implementation
* Populate the [args](https://github.com/demystifyfp/FsConfig/blob/master/src/FsConfig/Config.fs#L260)
* Extend `getTryParseFunc` [function](https://github.com/demystifyfp/FsConfig/blob/master/src/FsConfig/Config.fs#L118) to receive this args  and use the `IgnoreCase` attribute while doing tryParse in the Enum

I guess the last step involves some more work.

**Comment by piaste** [comment]
Thanks @demystifyfp. I can probably do that, and it would work just fine for my use case. I have actually been working on a different PR where these hints will be extremely useful (culture-invariant parsing of numerics and date values).

However, upon reflection I think I may have found a simpler approach. There's no reason why we can't keep performing the existing case-sensitive match, and then try a case-insensitive match _only_ if the case-sensitive one would crash.

This keeps backwards compatibility even in the case of a user having two enums case separated only by case. Honestly, I should have thought of it from the start (especially as we have a similar rule in our JSON.NET plugins).

With the added compatibility check, I thought it would be safe to apply the same rule to the parsing of discriminated unions, for consistency. I've added the corresponding tests, of course.

What do you think?

**Comment by demystifyfp** [comment]
I like this idea @piaste. 

I can merge this pull request if you are done. Also, can you update the documentation as well?

**Comment by piaste** [comment]
Yes, I'm OK with merging, thank you.

I've updated the docs as well in the `.fsx` source file, but I haven't been able to regenerate the markdown files because FAKE crashes with some cryptic SDK errors on my machine (I haven't used it in years). I'm going to have to ask you to run `GenerateDocs` yourself after the PR is merged.

**Comment by demystifyfp** [comment]
Thanks, @piaste for the pull request. It is now merged and latest version of FsConfig has this change. 

Sorry for the delayed response :)

**Pull request merged**
